In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import sys
a=range(2000)
print(sys.getsizeof(a))


48


In [4]:
import sys
a=range(2000)
print(sys.getsizeof(a)*len(a))

96000


In [5]:
d=np.arange(1000)
print(d.itemsize)
print(d.size*d.itemsize)

4
4000


In [7]:
b=np.array(42)
print(b)

42


In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [15]:
zeros_arr=np.zeros((5,2))
print(zeros_arr)
print(zeros_arr.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
float64


In [17]:
ze=np.zeros((3,3), dtype=np.int32)
#dtype=np.int32
print(ze)
print(ze.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [18]:
one=np.ones((6,6), dtype=np.int64)
print(one)
print(one.dtype)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
int64


In [20]:
e=np.empty((2,2))
print(e)
print(e.dtype)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.33511290e-306]]
float64


In [21]:
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
e=np.array([1,2,3] , dtype=np.int64)
print(e.dtype)
print(e)

int64
[1 2 3]


In [23]:
e=np.array([2,3,4])
print("Before converting",e.dtype)
a=e.astype('f')
print("After converting",a.dtype)

Before converting int32
After converting float32


In [27]:
e=np.arange(10)
a=np.random.randn(4)
c=e.astype(a.dtype)
print(e)
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 1.62963007 -0.60380166  0.93309146 -0.11360925]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [29]:
a=np.array(['hello','inte','floate'])
print(a)

['hello' 'inte' 'floate']


In [30]:
a=np.arange(9)
b=np.arange(9)
print(a+b)

[ 0  2  4  6  8 10 12 14 16]


In [31]:
a=np.array([1,2,3,4,5,6])
b=np.array([2,3,8,9,7,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 3  5 11 13 12 10]
[-1 -1 -5 -5 -2  2]
[ 2  6 24 36 35 24]
[0.5        0.66666667 0.375      0.44444444 0.71428571 1.5       ]


In [33]:
a=np.arange(16)
b=a.reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
a=np.arange(12)
b=a.reshape((3,4),order='F')
print(b)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [42]:
a=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4]])
b=a.reshape(3,2,2)
v=a.reshape(4,-1)
print(b)
print(v)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]

 [[7 8]
  [9 4]]]
[[1 2 3]
 [4 4 5]
 [6 7 7]
 [8 9 4]]


In [45]:
a=np.array([1,2,3,4])
b=a.flatten()
b[0]=588
print(a)
print(b)

[1 2 3 4]
[588   2   3   4]


In [46]:
a=np.array([1,2,3,4])
b=a.ravel()
b[2]=256
print(b)
print(a)

[  1   2 256   4]
[  1   2 256   4]


In [48]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,2,8],[6,8,7]])
c=a>b
d=a<b
e=a==b
print(c)
print(d)
print(e)

[[False False False]
 [False False False]]
[[ True False  True]
 [ True  True  True]]
[[False  True False]
 [False False False]]


In [50]:
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array_equal(a,b)
print(c)

True


In [52]:
x=np.array([1,2,3,4,5])
print(x[3:])
print(x[:3])
print(x[::-1])
print(x[1::4])
print(x[1::-3])
print(x)

[4 5]
[1 2 3]
[5 4 3 2 1]
[2]
[2]
[1 2 3 4 5]


In [ ]:
#indexing
a=np.array([[1,2,3,4],[2,3,4,5],[2,3,4,5]])